ICACHE module
FPGA-MAFIA/fpga_mafia pull request #768
Opened 2024-12-21 18:51 UTC by roman012285

In that PR, I designed a fully associative cache with 16 cache lines (CLs) and implemented a PLRU (Pseudo-Least Recently Used) replacement mechanism. To improve the design's throughput, I aimed to minimize the number of states in the state machine.

The `i_cache_top.sv` file contains two modules: one for the cache and the other for the PLRU tree algorithm. The testbench, `i_cache_top_tb.sv`, contains the test, which is relatively long. I verified the functionality using waveforms.

I haven’t connected the `i_mem.sv` itself to the cache yet, but I tested it, and it’s working. I have also created a forced delay of 8 cycles.

2024-12-21 20:50 UTC, amichai-bd requested changes
I will continue reviewing tomorrow

2024-12-21 20:50 UTC, amichai-bd commented on source/ifu/i_cache.sv
> +            default : ; // do nothing
It's better practice to add a default value

2024-12-21 20:50 UTC, amichai-bd commented on source/ifu/i_cache.sv
> +`MAFIA_LATCH(tag_valid_arr[lru_tag], 1'b1, latch_enable_fill)
This is interesting.. there is no reset condition..
This is fine because once a cache line is allocated, the entry will always be valid...

We may want to add a reset condition that will zero the cache during reset

2024-12-21 20:50 UTC, amichai-bd commented on source/ifu/i_cache.sv
> +            hit_array_q0[i] = 0;
Let's review this together and potentially improve the coding style

2024-12-21 20:50 UTC, amichai-bd commented on source/ifu/i_cache.sv
> +`MAFIA_LATCH(tag_valid_arr[lru_tag], 1'b1, latch_enable_fill)
No need for a new macro, just adjust the input and the enabled for all latches during reset

2024-12-21 20:50 UTC, amichai-bd commented on source/ifu/i_cache.sv
> +    input logic [31:0]                 pcQ100H,
Let's add a valid bit.

2024-12-21 20:50 UTC, amichai-bd commented on source/ifu/i_cache.sv
> +    input logic [$clog2(WAYS_NUM)-1:0] lru_tag,
The request and the response should have independent valid bits outside the structs

2024-12-21 20:50 UTC, amichai-bd commented on source/ifu/i_cache.sv
> +assign cache_full = (tag_valid_arr == 16'hffff);
We should be able to parametrize the cache size

2024-12-21 20:50 UTC, amichai-bd commented on source/ifu/i_cache.sv
> +`MAFIA_RST_DFF(cache2core_rsp.requested_instruction,instruction2core_q0,clk,rst)
that's also for timing reasons.. 16 way fully associative cache is a timing challenge.  And sampling the data is recommended.

2024-12-21 20:50 UTC, amichai-bd commented on source/ifu/i_cache_top.sv
> +plru plru
I think this PLRU logic should ne instantiated in the cache..

2024-12-21 20:50 UTC, amichai-bd commented on source/ifu/i_mem.sv
> +    input  logic [ADRS_WIDTH-1:0] address  , // TODO - possible to reduce size because we use only 28 bits pc[31:4]
We should reduce to 28 bits.

2024-12-21 20:50 UTC, amichai-bd commented on source/ifu/i_mem_wrap.sv
> +// Original Author  :
Add content

2024-12-22 10:50 UTC, roman012285 commented on source/ifu/i_cache.sv
> +            default : ; // do nothing
done

2024-12-22 10:51 UTC, roman012285 commented on source/ifu/i_cache.sv
> +    input logic [31:0]                 pcQ100H,
a valid bit is located inside structs towards the core and towards the i_mem

2024-12-22 10:53 UTC, roman012285 commented on source/ifu/i_cache.sv
> +    input logic [$clog2(WAYS_NUM)-1:0] lru_tag,
there are two structs `t_i_mem2cache_rsp` and `t_i_cache2imem_req`

2024-12-22 10:53 UTC, roman012285 commented on source/ifu/i_cache.sv
> +`MAFIA_RST_DFF(cache2core_rsp.requested_instruction,instruction2core_q0,clk,rst)
I will put a comment

2024-12-22 10:54 UTC, roman012285 commented on source/ifu/i_mem_wrap.sv
> +// Original Author  :
sure

2024-12-22 13:51 UTC, amichai-bd commented on source/ifu/i_cache.sv
> +    input logic [31:0]                 pcQ100H,
I know it's part of the struct.. I think we should have and independent valid bit instead of the valid in the structs..

2024-12-22 13:51 UTC, amichai-bd commented on source/ifu/i_cache.sv
> +            if(!cache_hit_q0) begin
Use 1'b1 instead of 1

2024-12-22 13:51 UTC, amichai-bd commented on source/ifu/plru.sv
> +task update_tree(input logic [$clog2(WAYS_NUM)-1:0] node);
This is not RTL code.. and there must be a better way to update the plru in coding style..

2024-12-24 17:38 UTC, roman012285 commented on source/ifu/i_cache_top.sv
> +plru plru
will be fixed

2024-12-24 17:39 UTC, roman012285 commented on source/ifu/plru.sv
> +task update_tree(input logic [$clog2(WAYS_NUM)-1:0] node);
fixed. macros added

2025-05-05 15:18 UTC, closed without merging