Ifu cache update
FPGA-MAFIA/fpga_mafia pull request #769
Opened 2024-12-22 13:00 UTC by abdkeb

change the the design of the cache,
using now always_comb blocks instead, 
defined new interface with cpu,
interface with prefetecher should be added latre

2024-12-22 13:28 UTC, amichai-bd reviewed
Good start

2024-12-22 13:28 UTC, amichai-bd commented on source/ifu/ifu_cache.sv
> +    parameter NUM_TAGS,      // Number of tags
Parameters that we don't expect to override in the instance could and should be part of the ifu package

2024-12-22 13:28 UTC, amichai-bd commented on source/ifu/ifu_cache.sv
> +task updatePLruTree(inout logic [NUM_LINES - 2 : 0 ] tree , input int line );
This is not code that is RTL compatible..

2024-12-22 13:28 UTC, amichai-bd commented on source/ifu/ifu_cache.sv
> +function int getPLRUIndex(logic [NUM_LINES - 2 : 0 ] tree);
This could be compatible with RTL,  but I do not recommend..
Macros or module are better options

2024-12-22 13:28 UTC, amichai-bd commented on source/ifu/ifu_cache.sv
> +        dataArray[freeLine] = mem_rspInsLineIn;
Looking at the Code seems like there are lots of latches that are not intended..
You should have explicit DFF for the arrays.

2024-12-22 14:02 UTC, roman012285 commented on source/ifu/ifu_cache.sv
> +    parameter NUM_TAGS,      // Number of tags
as amichai said, Please move the parameters into `ifu_package`. Its not an error its a preferred coding style in mafia

2024-12-26 21:41 UTC, amichai-bd requested changes
Make sure to have a different file for each module. 
Also make sure module name and file name match!

2024-12-26 21:41 UTC, amichai-bd commented on source/ifu/ifu_cache.sv
> +module updatePLruTree
We don't have 2 modules in the same file.

Each file one module, and the name of the module and the file must match

2025-01-06 17:26 UTC, roman012285 reviewed
good progress

2025-01-06 17:26 UTC, roman012285 commented on source/ifu/ifu_cache.sv
> +        dataArray[freeLine] = mem_rspInsLineIn;
To avoid latches, give some default value at the beginning of the always block (let me know if I was clear). Additionally, if you use  always_comb with inferred latches Quartus will give you an error

2025-01-06 17:26 UTC, roman012285 commented on source/ifu/ifu_cache.sv
> +task updatePLruTree(inout logic [NUM_LINES - 2 : 0 ] tree , input int line );
please use a function instead or macros if possible. as Amichai posted. Tasks can be synthesizable if you write synthesizable code inside them. Task may work but lets not use them for proper coding style

2025-01-06 17:26 UTC, roman012285 commented on verif/ifu/tb/ifu_cache_tb.sv
it's better to put all the parameters in the right package. If you use additional parameters for the test bench that are not in the package, then add them here.

2025-01-06 17:26 UTC, roman012285 commented on source/ifu/ifu_cache.sv
I see what you have been talking about. It's better to separate and put each module into different files.

2025-01-06 17:26 UTC, roman012285 commented on verif/ifu/tb/PLRU_tb.sv
out simulator does not support assertion. you don't have to use assertion. If you want we have a special macro inside `macros.vh` that imitates that but its not necessary to use it

2025-01-06 17:26 UTC, roman012285 commented on source/ifu/ifu.sv
It looks good the best way to evaluate it is to see it will work or not and how. good job

2025-01-06 17:26 UTC, roman012285 commented on source/ifu/ifu_pkg.sv
its not necessary to declare parameter al logic. when you declare something as logic, it can be 0,1,x, Z. Its not wrong but for consistent coding style its better not to use logic

2025-04-06 14:18 UTC, amichai-bd reviewed
I must say - your project looks great!
I would love to read the documentation once you got it all ready!

If you want me to review the documentation draft feel free to send it to me.

2025-04-06 14:18 UTC, amichai-bd commented on source/IDU/IDU_rtl_list.f
> +../../../source/IDU/IDU.sv
File name should be lower case

2025-04-06 14:18 UTC, amichai-bd commented on source/IDU/IDU.sv
File name should be lower case

2025-05-05 15:17 UTC, closed without merging